name: 'GitHub Actions Weather Bot'

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Weather'
        run: bash ./weather.sh
      - name: 'Get Date'
        run: echo "REPORT_DATE=$(TZ=':Asia/Hangzhou' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Shanghai Weather Report (${{env.REPORT_DATE}})
          html_body: file://result.html
          to: wforguo@gmail.com,987219323@qq.com,wforguo@qq.com,2364752192@qq.com
          from: GitHub Actions
